# Generated by Django 5.0.7 on 2024-07-26 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_body'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardingHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bh_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('capacity', models.IntegerField(default=0)),
                ('number_of_tenants', models.IntegerField(default=0)),
                ('number_of_rooms', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FaceImage',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('face_image', models.BinaryField()),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=255)),
                ('relationship', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('fingerprint', models.BinaryField()),
                ('face_image', models.BinaryField()),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('vault_password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.AutoField(primary_key=True, serialize=False)),
                ('room_number', models.CharField(max_length=15)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('available_beds', models.IntegerField(blank=True, null=True)),
                ('tenants', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('image_id', models.IntegerField()),
                ('gender', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('course_profession', models.CharField(max_length=255)),
                ('school_company', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15)),
                ('monthly_due', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monthly_due_date', models.DateField(blank=True, null=True)),
                ('initial_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenants', to='posts.guardian')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_date', models.DateField()),
                ('transaction_time', models.TimeField()),
                ('mode_of_payment', models.CharField(max_length=50)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('month_status', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AddField(
            model_name='boardinghouse',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.owner'),
        ),
        migrations.AddField(
            model_name='room',
            name='boarding_house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.boardinghouse'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='posts.room'),
        ),
        migrations.AddField(
            model_name='guardian',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='posts.tenant'),
        ),
        migrations.AddField(
            model_name='faceimage',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.tenant'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.tenant'),
        ),
    ]
