# Generated by Django 5.0.7 on 2024-07-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_owner_vault_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardinghouse',
            name='bh_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
